language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $714164183fd92b114c801c3f68ff1fe75ea72b36 # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master