sudo: false
language: node_js
node_js:
  - lts/*
install:
  - npm ci
branches:
  only:
    - master # build master branch only
script:
  - npm run docs:build
  - npm run cname
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $TravisCI # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master